version: '3.8'
services:
  mongo:
    image: mongo:4.2.21-bionic
    container_name: notes-app-node-react-mongo
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./mongodata:/data/db